credentials:
  usernames:
    tjm.plastica:
      email: tj@mail.com
      name: Thiago Jung
      password: $2b$12$3YaJs8IsoADGTL.PJnt5aeWWvSuad.QZXmTxBqVnDJOnCJjlAoRo. # To be replaced with hashed password
    dr.thiagojung:
      email: dr.tjmg@mail.com
      name: Dr. T. Jung
      password: $2b$12$SyQpGqcwuOLT14XoU.XnEOkLez6J8JPvQ5gbL4iUOMQ9ZBbOIMAYC # To be replaced with hashed password
    guest:
      email: guest@mail.com
      name: Guest
      password: $2b$12$.OSp9PiE0UKC1xpFiRazgOl/uYKFoJiAaJwehlPkCvAmttLZvRo6u # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: aws_streamlit_key # Must be string
  name: aws_streamlit_cookie
preauthorized:
  emails:
  - pre-auth@mail.com
